- R/bcdc_search.R
- Add english name string
- Add type of formats available
``` r
bcdc_search("snow")
#> List of B.C. Data Catalogue Records
#> 
#> Number of records: 28 (Showing the top 10)
#> Titles:
#> 1: Indicator Summary Data: Change in Snow Depth and Snow Water Content in BC (1950-2014)
#>  ID: 86526746-40dd-41d2-82c0-fbee3a2e93a2
#> 2: Automated Snow Weather Station Locations
#>  ID: ebe546aa-ac34-491c-a828-fdc87fb70610
#> 3: Archive Automated Snow Weather Station Data
#>  ID: 5e7acd31-b242-4f09-8a64-000af872d68f
#> 4: Current Season Manual Snow Survey Data
#>  ID: 12472805-6f6d-457b-8db2-5c1f42a00099
#> 5: Manual Snow Survey Locations
#>  ID: 9f653102-5627-45a7-bd4c-686e365ee04a
#> 6: Archive Manual Snow Survey Data
#>  ID: 705df46f-e9d6-4124-bc4a-66f54c07b228
#> 7: Current Season …
```
> Changes to search record print methods

- R/bcdc-web-services.R
- R/cql-translator.R
- R/utils.R
- tests/testthat/test-get-geodata.R
- A few code style modifications
- Add `check_geom_col_names` which queries the column names and if the record uses SHAPE, it edits the CQL query to use SHAPE. 
Here is the part that I am least confident in as it is a brute form approach to figuring out if SHAPE exists:
https://github.com/bcgov/bcdata/compare/geom_col_name?expand=1#diff-cbb7235afee10c3646161358a7655b0aR43
Comments welcome
> Geom col name

- R/cql-translator.R
- R/utils-classes.R
Hopefully addresses #46, and also may address #30
Likely requires cleanup of messy evaluation of cql expressions and spatial predicates.
> Allow partial evaluation so objects can be passed to filter statements.

- R/bcdc_search.R
- R/get_data.R
- R/utils.R
- R/zzz.R
- man/bcdc_describe_feature.Rd
- man/bcdc_get_data.Rd
- man/bcdc_get_geodata.Rd
- man/bcdc_get_record.Rd
- man/bcdc_preview.Rd
- man/bcdc_query_geodata.Rd
- tests/testthat/setup.R
- tests/testthat/teardown.R
- tests/testthat/test-utils.R
I opted to trigger one warning per session regardless of the function called. This is called in `bcdc_get_record()` which is called by many other functions: `bcdc_get_data()`, bcdc_query_geodata()`, `bcdc_preview()`, and `bcdc_describe_feature()`. So a call to any of those functions will trigger the warning.
I also added the ability for a user to suppress these warnings entirely (very useful for us in tests) by setting: `options("silence_named_get_record_warning" = TRUE)`
``` r
#> 
#> Attaching package: 'bcdata'
#> The following object is masked from 'package:stats':
#> 
#>     filter
bcdc_get_record("bc-airports")
#> Warning: It is advised to use the permanent id ('76b1b7a3-2112-4444-857a-
#> afccf7b20da8') rather than the name of the record ('bc-airports') to guard
#> …
```
> Warn once when user uses human-readable id rather than permament id

- R/utils-classes.R
- R/utils.R
- tests/testthat/test-query-geodata-filter.R
I've gone with a conservative number for the length of the vector that is too long for wfs because we arrived at iteratively. This will fail when filtering since that is the only wfs parameter that would balloon big enough to cause a problem.
> check for the length of the CQL_FILTER parameter and fail if too long

- R/get_data.R
- R/utils.R
Do not merge until #67 is ready to go. 
This might be a bit convoluted but I noticed that we were hard-coding supported file formats and their associated "read" functions in three places, which could cause headaches in the future - this consolidates them but at the cost of having slightly obscure code to actually get the function ready to read ([here](https://github.com/bcgov/bcdata/blob/f7c99d5544fdd376198560debf3eb905a5c2d3b5/R/utils.R#L226-L236))
We can either merge that first and then this, or merge this into `format_arg` branch and then the whole lot into master.
> Consolidate listing of file formats and associated 'read' functions

- R/utils-classes.R
- R/utils.R
- tests/testthat/test-query-geodata-filter.R
- tests/testthat/test-utils.R
This is a followup to #79, and closes #80. When successive `filter()` statements are called on a `bcdc_promise` object, they are stored as a vector of individual CQL filter statements. When required for execution (`show_query()`, `collect()`, `print.bcdc_promise()`) they are combined with `AND` using new function `finalize_cql()`
> Combine multiple filter statements

- R/get_data.R
- man/bcdc_describe_feature.Rd
- man/bcdc_get_data.Rd
- man/bcdc_get_geodata.Rd
- man/bcdc_preview.Rd
- man/bcdc_query_geodata.Rd
- tests/testthat/test-get-data.R
Provides a method for a user to call `bcdc_get_data()` on a `bcdc_record` (i.e., the result of calling `bcdc_get_record('catalogue_url-or-record_id;)`.
Abstracts out the core of `bcdc_get_data()` into a new internal function, which both methods now call. Also provides a default method which throws an informative error if a user tries to use something other than a character string or `bcdc_record` object
> bcdc_record method for bcdc_get_data

- R/cql-geom-predicates.R
- R/describe-feature.R
- R/utils-classes.R
- R/utils.R
- tests/testthat/test-cql-string.R
- tests/testthat/test-query-geodata-collect.R
- tests/testthat/test-query-geodata-filter.R
This represents a major change to we access the WFS, accessing data via a `post` method rather than `get` method. As a result a simple url is no longer an accurate means of conveying how the query to WFS was carried out. As a result both `show_query` methods have been altered to reflect this.
Additional changes:
- A threshold of 500000B for the interesect object has been established, above which a bounding box is drawn.
- In the paginated response, I am trying to catch curl errors and just let the user know something went wrong, likely on the server side. 
- Because we are sending queries in the body of a `post`, issues raised in #55 no longer applies.
> Implement post method

- R/get_data.R
- R/utils-classes.R
- R/utils.R
- README.Rmd
- README.md
- tests/testthat/test-get-data.R
- vignettes/bcdata.Rmd
This allows zip resources to be downloaded and read in, and adds support for `.shp`, `.gpkg`, and `.gdb` files. It extracts the zip file and fails if there is more (or less) than one type of supported file, otherwise reads any supported file type normally. 
I think this opens the door for more failures, so I also added a `tryCatch` statement around the reading to give a more informative error message if reading fails.
Closes #84
> Read data from zip files

- .Rbuildignore
- .travis.yml
- DESCRIPTION
- R/bcdc-web-services.R
- R/describe-feature.R
- R/get_data.R
- R/utils-classes.R
- R/utils-is.R
- R/utils.R
- README.Rmd
- README.md
- codecov.yml
- man/bcdc_describe_feature.Rd
- man/bcdc_get_data.Rd
- man/bcdc_preview.Rd
- man/bcdc_query_geodata.Rd
- tests/testthat/test-describe-feature.R
- tests/testthat/test-query-geodata-filter.R
- tests/testthat/test-query-geodata-select.R
- tests/testthat/test-query-geodata.R
- tests/testthat/test-utils.R
WIP for #106 (not ready for merge).
Still to do:
``` r
library(sf)
good1 <- bcdc_query_geodata("WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW") %>% 
collect()
good2 <- bcdc_get_data("WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW")
box <- st_as_sfc(st_bbox(c(xmin = 506543.662, ymin = 467957.582, 
xmax = 1696644.998, ymax = 1589145.873), 
crs = 3005))
good3 <- bcdc_query_geodata("bc-airports") %>% 
filter(WITHIN(box)) %>% 
collect()
bcdc_query_geodata("WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW") %>% 
filter(WITHIN(box)) %>% 
collect()
#> Warning: Unable to determine the name of the geometry column; assuming
#> 'GEOMETRY'
#> Warning in bcdc_number_wfs_records(query_list, cli): NAs introduced by
#> coercion
#> Error in if (number_of_records < 10000) {: missing value where …
```
> Allow functions to accept name of BCGW object

- R/cql-geom-predicates.R
- tests/testthat/test-cql-string.R
The behaviour is now:
```
> bcdc_query_geodata("6a2fea1b-0cc4-4fc2-8017-eaf755d516da") %>%
filter(PARK_PRIMARY_USE == "Park") %>% 
filter(INTERSECTS(districts))
Error: object "districts" not found.
The object passed to INTERSECTS needs to be valid sf object.
```
I would appreciate a 2nd set of eyes here.
> better general handling of objects not found. Closes #130

- NEWS.md
- R/bcdc-web-services.R
- tests/testthat/test-edge-cases.R
Rather than pull the layer name to pass to the `typeNames` parameter in the WFS request, this gets it from the url of the wfs resource. This is because records have both a `layer_name` and an `object_name` and you can't count on the wfs/wms to use a particular one. See #138 and #129.
I also added a new test file for these kinds of edge cases.
One more thing that could be added to this PR is fixing #133, as it is related.
> Get typeName for wfs from resource url

- R/utils-classes.R
- tests/testthat/test-search.R
What about this error message?
```
> bcdc_search("Major Railways")
List of B.C. Data Catalogue Records
Number of records: 2
Titles:
1: (7.5M) Major Railways - The Atlas of Canada Base Maps for BC
This record has no resources. bcdata will not be able to access any data.
ID: 7b6d9196-7036-4b9a-bb78-e13b1d08068a
Name: 7-5m-major-railways-the-atlas-of-canada-base-maps-for-bc
2: (7.5M) Major Railways - The Atlas of Canada Base Maps (other)
ID: c894310a-1f86-419f-b0ac-c5a71a8ff2e5
Name: 7-5m-major-railways-the-atlas-of-canada-base-maps 
Access a single record by calling bcdc_get_record(ID)
with the ID from the desired record.
```
> record_list no longer fails when a record has no resources. Closes #128

- DESCRIPTION
- NEWS.md
- R/cql-geom-predicates.R
- R/cql-translator.R
- man/cql_geom_predicates.Rd
- tests/testthat/test-cql-string.R
- tests/testthat/test-geom-operators.R
Allow geometry predicates (E.g., `INTERSECTS()`, `BBOX()` etc) to accept `bbox` objects in addition to `sf*` objects. Also allows the `crs` argument of `BBOX()` to be a numeric EPSG code (not just character: `"EPSG:3005"`
> bbox fixes

- NEWS.md
- R/get_data.R
- R/utils.R
- man/bcdc_get_data.Rd
- tests/testthat/test-get-data.R
Here is what happens at the moment:
``` r
#> Attaching package: 'bcdata'
#> The following object is masked from 'package:stats':
#> 
#>     filter
bcdc_get_data('8620ce82-4943-43c4-9932-40730a0255d6')
#> Reading the data using the read_xlsx function from the readxl package.
#> 
#> This .xlsx resource contains the following sheets: 
#>  'Notes'
#>  'Regional Districts'
#>  'Single Detached'
#>  'Multi Unit Homes'
#>  'Purpose Built Rental'
#> Defaulting to the 'Notes' sheet. See ?bcdc_get_data for examples on how to specify a sheet.
#> # A tibble: 0 x 0
bcdc_get_data('8620ce82-4943-43c4-9932-40730a0255d6', sheet = "Single Detached")
#> Reading the data using the read_xlsx function from the readxl package.
#> 
#> This .xlsx resource contains the following sheets: 
#> …
```
> handle excel sheets #190

- NEWS.md
- R/bcdc-web-services.R
- R/get_data.R
- tests/testthat/test-get-data.R
- tests/testthat/test-query-geodata-collect.R
> bcdc_get_data and bcdc_query_geodata with full url including resource

- NEWS.md
- R/utils-classes.R
- tests/testthat/test-query-geodata-collect.R
This add when a layer is downloaded which is useful information no matter what. I also think that this could be useful for incorporating bcdata into bcmaps.
> add time_downloaded as attribute to bcdc_sf

- R/utils-classes.R
- R/utils.R
- tests/testthat/test-query-geodata-filter.R
- tests/testthat/test-query-geodata-head-tail.R
- tests/testthat/test-query-geodata-select.R
This PR fixes a bug that caused paginated requests to fail with `head`. For example this now works:
```  
dh <- bcdc_query_geodata('2af1388e-d5f7-46dc-a6e2-f85415ddbd1c') %>%
head(3) %>%
collect()
```
by telling the `bcdc_number_wfs_records` function to look out for a count parameter and use that if it exists. 
However, I am unable to make tail work. This does not currently work:
```  
dh <- bcdc_query_geodata('2af1388e-d5f7-46dc-a6e2-f85415ddbd1c') %>%
tail(3) %>%
collect()
```
As far as I can see, the _only_ difference is that a `tail` "query" includes a `startIndex` query parameter. I haven't yet been able to figure this out. 
`tail` _does_ work for a smaller query like this:
```
bcdc_query_geodata('hydrometric-stations-active-and-discontinued') %>% 
tail(3) %>% 
collect() 
```
> Make head/tail work with larger queries

- .github/workflows/cmd-check.yaml
- NEWS.md
- R/bcdc-web-services.R
- R/bcdc_browse.R
- R/bcdc_options.R
- R/bcdc_search.R
- R/cql-geom-predicates.R
- R/describe-feature.R
- R/get_data.R
- R/utils-classes.R
- man/bcdc_browse.Rd
- man/bcdc_describe_feature.Rd
- man/bcdc_get_data.Rd
- man/bcdc_get_record.Rd
- man/bcdc_list.Rd
- man/bcdc_options.Rd
- man/bcdc_preview.Rd
- man/bcdc_query_geodata.Rd
- man/bcdc_search.Rd
- man/bcdc_search_facets.Rd
- man/bcdc_tidy_resources.Rd
- man/collect-methods.Rd
- man/filter.Rd
- man/mutate.Rd
- man/select.Rd
- man/show_query.Rd
Set up GH Actions to run the examples that are wrapped in `donttest{}`
Files to be checked for examples that hit the web services, and wrap those in `try()`:
> Guard against check failures in examples

- R/utils-classes.R
- tests/testthat/test-utils-classes.R
Parameter name `limit_chunk` does not match `chunk` in `?crul::Paginator` documentation.
```r
bec <- bcdc_get_data(bcdc_search("BEC Map")[[1]])
```
Current call to `Paginator$new` will complain about parameter `limit_chunk` being unused.
I check `crul` commits history, and they changed `limit_chunk` to `chunk` 6 months ago.
Great package. Godspeed.
> fix parameter in methods

- NEWS.md
- R/bcdc_options.R
- R/utils-classes.R
- R/utils.R
- R/zzz.R
- tests/testthat/test-options.R
This PR:
- Create a `bcdc_single_download_limit` function
- Tests that function
- Uses that function to set the "bcdata.single_download_limit" on package load
- Directly access that option is a few functions
Not yet implemented:
~- A test that makes sure one can reset that option.~
> Extract download limits directly from WFS

- DESCRIPTION
Fixes this NOTE: https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/bcdata-00check.html
we don't have any internal data in bcdata so I think this is ok.
> remove lazy data

- R/utils-classes.R
- tests/testthat/test-options.R
> create paginated only print msg

- NEWS.md
- R/bcdc_options.R
- R/bcdc_search.R
- R/zzz.R
- man/bcdc_list_group_records.Rd
- tests/testthat.R
- tests/testthat/test-options.R
- tests/testthat/test-utils.R
See warning: https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/bcdata-00check.html
- Remove bcdc_get_wfs_records_xml from onLoad:
- set get_capabilities_xml to NULL on pkg load
- bcdc_get_wfs_records_xml() retrieves xml on first request and store for rest of the session
- eliminate some redundant messages
- Wrap example in try(), add missing skip_if_net_down()
> Fix potential onLoad failure from getCapabilities call

- .github/workflows/cmd-check.yaml
- NEWS.md
- R/get_data.R
- tests/testthat/test-get-data.R
Tests are currently failing because one of our test records changed the resource id. This illustrated that we don't actually have a check to ensure a requested resource exists in a record. This fixes that (along with a new test), and fixes the failing test by using the new resource ID.
> Fail informatively when resource doesn't exist

- R/cql-translator.R
Fixes CRAN check NOTE at: https://cran.r-project.org/web/checks/check_results_bcdata.html. The `dbplyr` generic `sql_translation()` has argument name `con`, we had `conn`
> S3 generic/method consistency

- inst/CITATION
CRAN wants people to use the [newer citation format `bibentry()`](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#CITATION-files), else we may get this NOTE:
```
Package CITATION file contains call(s) to citEntry(), citHeader() or
citFooter().  Please use bibentry() instead.
```
> use new citation style

- DESCRIPTION
- NEWS.md
- R/bcdc-web-services.R
- R/bcdc_options.R
- R/utils-classes.R
- R/zzz.R
- man/bcdc_options.Rd
- man/bcdc_query_geodata.Rd
- scratch/scratch_test_iterating.R
- tests/testthat.R
- tests/testthat/_snaps/options.md
- tests/testthat/test-bcdc-get-citation.R
- tests/testthat/test-browse.R
- tests/testthat/test-cql-string.R
- tests/testthat/test-describe-feature.R
- tests/testthat/test-edge-cases.R
- tests/testthat/test-geom-operators.R
- tests/testthat/test-get-data.R
- tests/testthat/test-get_record.R
- tests/testthat/test-options.R
- tests/testthat/test-print-methods.R
- tests/testthat/test-query-geodata-base-methods.R
- tests/testthat/test-query-geodata-collect.R
- tests/testthat/test-query-geodata-filter.R
- tests/testthat/test-query-geodata-mutate.R
- tests/testthat/test-query-geodata-select.R
- tests/testthat/test-query-geodata.R
- tests/testthat/test-search.R
- tests/testthat/test-utils.R
#330 surfaced the change to the single download limit on the WFS server to 500 records (down from 10,000). This exposed the potential incompatibility between `bcdcd.single_download_limit` and `bcdc.chunk_limit` options, where it was possible for the latter to be larger than the former. Since `bcdcd.single_download_limit` determined whether or not we needed pagination for a request, and `bcdc.chunk_limit` is used to determined the page size (number of records requested in a page), we were getting into the situation where we were attempting to retrieve more records in a page than is allowed by the server.
This PR sets the default chunk limit to the `bcdc.single_download_limit` by default, and also checks more comprehensively that the two values are compatible.
This address part of #330, but …
> Reconcile chunk_limit and single_download_limit

- R/bcdc_options.R
- R/utils.R
DSS fixed the ows GetCapabilities endpoint (https://openmaps.gov.bc.ca/geo/pub/ows?service=WFS&version=2.0.0&request=GetCapabilities) so we no longer need to switch to http for this one call. 
Closes #329
> No longer need http for getCapabilities request. #329

- R/bcdc-web-services.R
- man/bcdc_query_geodata.Rd
In response to #355 and #227 
May not solve the integration  of `CQL()` or `str_*` or `grep` but these new examples that use `%LIKE%` and `%IN%` will be useful for a number of use cases.
> added example of partial query using %like% and %in%

- tests/testthat/test-cql-string.R
This small typo is leading to a CRAN check error in R devel due to modifying attributes of a primitive function: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/bcdata-00check.html.
```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-cql-string.R:23:3'): bcdc_cql_string fails when used on an uncollected (promise) object ──
Error in `attributes(.Data) <- c(attributes(.Data), attrib)`: Cannot modify attributes on primitive functions
Backtrace:
▆
1. ├─testthat::expect_error(...) at test-cql-string.R:23:3
2. │ └─testthat:::expect_condition_matching(...)
3. │   └─testthat:::quasi_capture(...)
4. │     ├─testthat (local) .capture(...)
5. │     │ └─base::withCallingHandlers(...)
6. │ …
```
> fix missing parens to fix R CMD check error on R-devel
